### PR TITLE
Fix Builds

### PR DESCRIPTION
**Pull request by p-groarke**
The cmake file for 3.3 states it requires mongo-c >= 1.10, so I bumped the version to 1.11.

I fixed the build for MSVC and cleaned up the "magic" hack. I can't test on unixes, but setting the definitions the right way shouldn't change anything. Travis will be a nice boi and confirm that.

Removed unsupported MSVC version and added lib renaming for windows (it doesn't prepend libs with `lib`).

Switched unixes to Boost.

Cheers and good day

### CODE REVIEW

**Comment by uilianries** [comment]
Thanks for helping us with this one!

There is some error when running the test_package on Windows:

```
mongo-cxx-driver/3.3.0@bincrafters/stable (test package): Running test()
Traceback (most recent call last):
  File "build.py", line 11, in <module>
    builder.run()
  File "C:\Python27\lib\site-packages\cpt\packager.py", line 449, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\Python27\lib\site-packages\cpt\packager.py", line 529, in run_builds
    r.run()
  File "C:\Python27\lib\site-packages\cpt\runner.py", line 99, in run
    test_folder=self._test_folder)
  File "C:\Python27\lib\site-packages\conans\client\conan_api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\conans\client\conan_api.py", line 376, in create
    test_build_folder, test_folder, conanfile_path)
  File "C:\Python27\lib\site-packages\conans\client\cmd\create.py", line 41, in create
    test_build_folder=test_build_folder)
  File "C:\Python27\lib\site-packages\conans\client\cmd\test.py", line 46, in install_build_and_test
    install_folder=test_build_folder, test=str(reference))
  File "C:\Python27\lib\site-packages\conans\client\cmd\build.py", line 59, in build
    conan_file.test()
  File "C:\Python27\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python27\lib\site-packages\conans\errors.py", line 30, in conanfile_exception_formatter
    raise ConanExceptionInUserConanfileMethod(msg)
conans.errors.ConanExceptionInUserConanfileMethod: mongo-cxx-driver/3.3.0@bincrafters/stable (test package): Error in test() method, line 21
	self.run(bin_path)
	ConanException: Error -1073741515 while executing bin\test_package
Command exited with code 1
```

Are you able to reproduce such error on your side?

**Comment by p-groarke** [comment]
@uilianries Nope, this last commit was supposed to fix it. Everything builds, packages and tests on my side. Will look into it when I have some more free time.

**Comment by uilianries** [comment]
I'll try to reproduce it later

**Comment by p-groarke** [comment]
It seems to have issues with the test binary path. I'm guessing the CI folder hierarchy is somewhat different than my local test.

**Comment by SSE4** [comment]
@uilianries ping

**Comment by uilianries** [comment]
sorry, I forgot this one!

**Comment by uilianries** [comment]
I'm able to reproduce on my machine. When the test package is execute, the application throws an error: "bsoncxx.dll not found"

**Comment by p-groarke** [comment]
@uilianries Nice!

**Comment by p-groarke** [comment]
For the unixes, cmake is not compiling in c++11 mode for some reason. I didn't take time to investigate, but I don't think there is much left to get it working.

**Comment by uilianries** [comment]
I gonna check today again :muscle:

**Comment by p-groarke** [comment]
Considering all platforms aren't building, it might be worth merging these fixes. They get us much closer to the end goal.

**Pull request merged**
